defaultEntryPoints = [ "http", "https"]

[web]
address = ":8080"
  [web.auth.basic]
  users = ["admin:$apr1$9zkm5Fz9$g6Xpp34jFSj4WBN0H0lxU."]

[entryPoints]
  [entryPoints.http]
    address  = ":80"
    compress = true
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]

[acme] # LetsEncrypt config
  email      = "sysadmin@tams.tech"
  entryPoint = "https"
  storage    = "/etc/letsencrypt_store.json"
  onHostRule = true
  onDemand   = false
